-- Canonical content store for the blog CMS.
-- UUIDs are generated by the application so the schema stays portable to PostgreSQL.

CREATE TABLE categories (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL COLLATE NOCASE UNIQUE,
  name TEXT NOT NULL COLLATE NOCASE UNIQUE,
  description TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

CREATE TABLE posts (
  id TEXT PRIMARY KEY,
  category_id TEXT REFERENCES categories(id) ON DELETE SET NULL,
  slug TEXT NOT NULL COLLATE NOCASE UNIQUE,
  title TEXT NOT NULL CHECK (length(title) BETWEEN 1 AND 90),
  summary TEXT NOT NULL DEFAULT '' CHECK (length(summary) <= 240),
  -- The canonical, editable Tiptap document (JSON.stringify(editor.getJSON())).
  content_json TEXT NOT NULL CHECK (json_valid(content_json)),
  -- Plain text derived from content_json on save; used for reading time and search.
  content_text TEXT NOT NULL DEFAULT '',
  cover_image_url TEXT,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'published', 'archived')),
  published_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (
    (status = 'published' AND published_at IS NOT NULL)
    OR status IN ('draft', 'archived')
  )
);

CREATE TABLE tags (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL COLLATE NOCASE UNIQUE,
  name TEXT NOT NULL COLLATE NOCASE UNIQUE,
  created_at TEXT NOT NULL
);

CREATE TABLE post_tags (
  post_id TEXT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY (post_id, tag_id)
);

-- Public routes and admin list queries.
CREATE INDEX posts_status_published_at_idx ON posts(status, published_at DESC);
CREATE INDEX posts_category_status_published_at_idx
  ON posts(category_id, status, published_at DESC);
CREATE INDEX post_tags_tag_id_post_id_idx ON post_tags(tag_id, post_id);

INSERT INTO categories (id, slug, name, description, sort_order, created_at) VALUES
  ('cat_work_craft', 'work-craft', 'WORK & CRAFT', '일과 도구에 관한 기록', 10, '2026-07-18T00:00:00.000Z'),
  ('cat_tech', 'tech', 'TECH', '기술과 만드는 과정에 관한 기록', 20, '2026-07-18T00:00:00.000Z'),
  ('cat_life', 'life', 'LIFE', '일상과 관찰에 관한 기록', 30, '2026-07-18T00:00:00.000Z'),
  ('cat_note', 'note', 'NOTE', '짧은 메모', 40, '2026-07-18T00:00:00.000Z');
